// Code generated by cmd/ecl-sky-colours; DO NOT EDIT.

package game

// eclBlockLoadTimeWrites 是每一段 ECL **載入存檔時真的會跑到**的常數寫入，
// 只收 remake 需要而原作靠跑進入碼才有的那幾格（`cmd/ecl-sky-colours`，spec 1185）。
//
//	4BE7h／4BE8h  `37h LOAD PIECES` 的兩槽模式閘門（spec 1087）
//	4BFDh／4BFEh  室外／室內天空選色（存檔 Area1 的 `01FAh`／`01FCh`）
//
// ★ 為什麼要有這張表。 remake 載入存檔時不重跑該段的進入碼（會連帶觸發劇情
// 副作用），這幾格會停在底檔（別章）的值。原版在同一份存檔上會跑，於是兩邊
// 分岔——而天空是一整片純色，錯的顏色也是一整片純色，**看不出異常**。
//
// ⚠ 鍵是 **ECL 段**，不是地圖。GEO5 的 `0x31`／`0x32` 共用同一張幾何區塊。
//
// ⚠ 收集走的是 `ecl.ReachableOnLoad`：段的開頭幾乎都有一道
// `COMPARE 4BF2h, <段號>` 的閘門，而那道閘門**兩個方向都有人用**。只掃
// 「有沒有這條 `SAVE`」會多收，而多收的後果是把沒被推翻的值改掉。
var eclBlockLoadTimeWrites = map[eclBlockKey]map[uint16]uint16{
	{area: 2, block: 0x01}: {0x4BFE: 9},
	{area: 3, block: 0x15}: {0x4BFD: 8, 0x4BFE: 8},
	{area: 4, block: 0x20}: {0x4BFD: 11, 0x4BFE: 13},
	{area: 5, block: 0x31}: {0x4BFD: 11, 0x4BFE: 10},
	{area: 5, block: 0x32}: {0x4BFE: 10},
	{area: 5, block: 0x33}: {0x4BFD: 11, 0x4BFE: 10},
	{area: 5, block: 0x35}: {0x4BE7: 1, 0x4BE8: 1, 0x4BFE: 10},
	{area: 6, block: 0x40}: {0x4BFD: 11, 0x4BFE: 13},
	{area: 6, block: 0x42}: {0x4BFD: 11, 0x4BFE: 13},
	{area: 6, block: 0x43}: {0x4BFE: 13},
	{area: 6, block: 0x45}: {0x4BE7: 1, 0x4BE8: 1, 0x4BFD: 11},
}
