// Code generated by cmd/ecl-sky-colours; DO NOT EDIT.

package game

// eclBlockSkyColours 是每一段 ECL 進入時寫進 `4BFDh`／`4BFEh` 的天空選色，
// 逐段從原版 ECL 位元組碼掃出來（`cmd/ecl-sky-colours`，spec 1185）。
//
// ★ 為什麼要有這張表。 那兩格就是存檔 Area1 的 `OutdoorSkyColor`／`IndoorSkyColor`
// （位元組位移 `01FAh`／`01FCh`）。載入原版存檔時 remake 不重跑該段的進入碼，
// 兩格會停在底檔（別章）的值；原版在同一份存檔上會跑，於是天空整片是另一個顏色，
// 而畫面看起來完全正常——純色錯成另一個純色，沒有任何破圖可以提示。
//
// ⚠ 鍵是 **ECL 段**，不是地圖。GEO5 的 `0x31`／`0x32` 共用同一張幾何區塊，
// 選色卻不同。
//
// ⚠ 值是**選色索引**，引擎再查 `skyPalette` 才得到 EGA 色號。
// `-1` ＝ 這一段沒有寫那一格，維持存檔帶進來的值。
var eclBlockSkyColours = map[eclBlockKey]skyColours{
	{area: 2, block: 0x01}: {Outdoor: -1, Indoor: 9},
	{area: 3, block: 0x15}: {Outdoor: 8, Indoor: 8},
	{area: 4, block: 0x20}: {Outdoor: 11, Indoor: 13},
	{area: 5, block: 0x31}: {Outdoor: 11, Indoor: 10},
	{area: 5, block: 0x32}: {Outdoor: -1, Indoor: 10},
	{area: 5, block: 0x33}: {Outdoor: 11, Indoor: 10},
	{area: 5, block: 0x35}: {Outdoor: -1, Indoor: 10},
	{area: 6, block: 0x40}: {Outdoor: 11, Indoor: 13},
	{area: 6, block: 0x42}: {Outdoor: 11, Indoor: 13},
	{area: 6, block: 0x43}: {Outdoor: -1, Indoor: 13},
	{area: 6, block: 0x45}: {Outdoor: 11, Indoor: -1},
}

// skyColours 是一段 ECL 的兩個選色索引；-1 表示那一段沒有設定。
type skyColours struct {
	Outdoor int
	Indoor  int
}
