// Command ecl-wall-pieces 盤點每一個 ECL block 發出的 `37h LOAD PIECES` 三元組。
//
// ★ 存在的理由是回答一個 yes／no：**同一個 block 會不會發出不只一組牆磚選圖？**
//
// 這個問題有實際後果。載入原版存檔之後，remake 沒有重跑 block 的進入碼，於是
// `LoadPieces` 是全零——第一人稱把每一面牆都畫成空氣，而畫面看起來完全正常
// （spec 1185）。要修有兩條路：重跑進入碼（會連帶觸發劇情副作用），或是照
// 地圖查一組固定的選圖。**後者只有在「一個 block 只發一組」成立時才是對的**，
// 而那不是可以用猜的——所以先量。
//
// ⚠ 只收**常數**運算元。`37h` 的運算元可以是記憶體參照，那種值要看執行時的
// 記憶體，靜態掃不出來；把它們混進「這個 block 就是這一組」會得到一個自洽但
// 錯的結論。它們單獨列在報表的最後一段。
//
// 用法：
//
//	go run ./cmd/ecl-wall-pieces -output docs/audit/ecl-wall-pieces.md
package main

import (
	"archive/zip"
	"flag"
	"fmt"
	"github.com/wicanr2/Curse-of-the-Azure-Bonds-cht/internal/tooltext"
	"io"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/wicanr2/golden-box-remake-engine/dax"
	"github.com/wicanr2/Curse-of-the-Azure-Bonds-cht/internal/ecl"
)

type siteKey struct {
	member string
	block  uint8
}

type blockReport struct {
	key       siteKey
	constant  map[[3]uint16]int
	dynamic   int
	anyOffset int
}

func main() {
	imagePath := flag.String("image", "curseoftheazurebonds.zip", tooltext.Text("h.5d993e050e0a"))
	output := flag.String("output", "", tooltext.Text("h.78eb014c7900"))
	goOutput := flag.String("go-output", "", tooltext.Text("h.30b45157eb45"))
	flag.Parse()

	archive, err := zip.OpenReader(*imagePath)
	if err != nil {
		log.Fatal(err)
	}
	defer archive.Close()

	reports := map[siteKey]*blockReport{}
	for member := 1; member <= 6; member++ {
		name := fmt.Sprintf("ECL%d.DAX", member)
		payload := memberPayload(&archive.Reader, name)
		if payload == nil {
			continue
		}
		blocks, parseErr := dax.Parse(payload)
		if parseErr != nil {
			log.Fatalf("%s：%v", name, parseErr)
		}
		for _, block := range blocks {
			scanBlock(reports, siteKey{member: name, block: block.Entry.ID}, block.Data)
		}
	}

	keys := make([]siteKey, 0, len(reports))
	for key := range reports {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].member != keys[j].member {
			return keys[i].member < keys[j].member
		}
		return keys[i].block < keys[j].block
	})

	single, multi, dynamicOnly := 0, 0, 0
	var report strings.Builder
	fmt.Fprint(&report, tooltext.Format("h.fddcbc6a7aeb"))
	fmt.Fprint(&report, tooltext.Format("h.23d7cc0b23fb"))
	fmt.Fprint(&report, tooltext.Format("h.01a454ef287a"))
	fmt.Fprintf(&report, "|---|---:|---|---:|---:|\n")
	for _, key := range keys {
		item := reports[key]
		triples := make([][3]uint16, 0, len(item.constant))
		for triple := range item.constant {
			triples = append(triples, triple)
		}
		sort.Slice(triples, func(i, j int) bool {
			for k := 0; k < 3; k++ {
				if triples[i][k] != triples[j][k] {
					return triples[i][k] < triples[j][k]
				}
			}
			return false
		})
		rendered := make([]string, 0, len(triples))
		for _, triple := range triples {
			rendered = append(rendered, fmt.Sprintf("`%d,%d,%d`×%d", triple[0], triple[1], triple[2], item.constant[triple]))
		}
		switch {
		case len(triples) == 1:
			single++
		case len(triples) > 1:
			multi++
		default:
			dynamicOnly++
		}
		fmt.Fprintf(&report, "| `%s` | `0x%02X` | %s | %d | %d |\n",
			key.member, key.block, strings.Join(rendered, " "), len(triples), item.dynamic)
	}

	fmt.Fprint(&report, tooltext.Format("h.5c124748e95b"))
	fmt.Fprint(&report, tooltext.Format("h.19de0e49904f", single))
	fmt.Fprint(&report, tooltext.Format("h.d1ba5365c7b2", multi))
	fmt.Fprint(&report, tooltext.Format("h.4e942598fca3", dynamicOnly))

	fmt.Fprint(&report, tooltext.Text("h.6d861c7ca560")+
		tooltext.Text("h.44281d59337b")+
		tooltext.Text("h.a65630e46caa"))

	if *goOutput != "" {
		var code strings.Builder
		fmt.Fprintf(&code, "// Code generated by cmd/ecl-wall-pieces; DO NOT EDIT.\n\n")
		fmt.Fprintf(&code, "package game\n\n")
		fmt.Fprint(&code, tooltext.Format("h.500729965004"))
		fmt.Fprint(&code, tooltext.Format("h.c5a3caea2d70"))
		fmt.Fprintf(&code, "//\n")
		fmt.Fprint(&code, tooltext.Format("h.0da5e5aedb12"))
		fmt.Fprint(&code, tooltext.Format("h.2649f560f69d"))
		fmt.Fprint(&code, tooltext.Format("h.2703136ade42"))
		fmt.Fprintf(&code, "//\n")
		fmt.Fprint(&code, tooltext.Format("h.d8f64a0af7ac"))
		fmt.Fprint(&code, tooltext.Format("h.ff604587be92"))
		fmt.Fprint(&code, tooltext.Format("h.d14f893ec0aa"))
		fmt.Fprintf(&code, "//\n")
		fmt.Fprint(&code, tooltext.Format("h.0b3af59058c5", len(keys)))
		fmt.Fprint(&code, tooltext.Format("h.6f7512f8bddb"))
		fmt.Fprintf(&code, "var eclBlockWallPieces = map[eclBlockKey][3]uint16{\n")
		for _, key := range keys {
			item := reports[key]
			for triple := range item.constant {
				member := strings.TrimSuffix(strings.TrimPrefix(key.member, "ECL"), ".DAX")
				fmt.Fprintf(&code, "\t{area: %s, block: 0x%02X}: {%d, %d, %d},\n",
					member, key.block, triple[0], triple[1], triple[2])
			}
		}
		fmt.Fprintf(&code, "}\n\n")
		fmt.Fprintf(&code, "type eclBlockKey struct {\n\tarea  uint8\n\tblock uint8\n}\n")
		if err := os.WriteFile(*goOutput, []byte(code.String()), 0o644); err != nil {
			log.Fatal(err)
		}
	}

	text := report.String()
	if *output == "" {
		fmt.Print(text)
	} else if err := os.WriteFile(*output, []byte(text), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Fprintf(os.Stderr, "blocks=%d single=%d multi=%d dynamic-only=%d\n",
		len(keys), single, multi, dynamicOnly)
}

// scanBlock 只收**載入存檔時真的會跑到**的 `37h`。
//
// ⚠ 走 `ecl.ReachableOnLoad`，不是整張 trace graph：段的前置常被
// `COMPARE 4BF2h, <段號>` 的閘門擋著，而那道閘門兩個方向都有人用。
// 只掃「有沒有這條 `37h`」會收到載檔時根本不會發的選圖，而 remake 拿它去覆蓋
// 存檔的值，牆就換成另一組——畫面看起來完全正常（spec 1185）。
func scanBlock(reports map[siteKey]*blockReport, key siteKey, data []byte) {
	instructions, err := ecl.ReachableOnLoad(data, key.block)
	if err != nil {
		return
	}
	for _, instruction := range instructions {
		if instruction.Command.Opcode != 0x37 {
			continue
		}
		item := reports[key]
		if item == nil {
			item = &blockReport{key: key, constant: map[[3]uint16]int{}}
			reports[key] = item
		}
		var triple [3]uint16
		constant := true
		for index, operand := range instruction.Operands {
			if index > 2 {
				break
			}
			value, ok := constantOperand(operand)
			if !ok {
				constant = false
				break
			}
			triple[index] = value
		}
		if !constant {
			item.dynamic++
			continue
		}
		item.constant[triple]++
	}
}

func memberPayload(archive *zip.Reader, name string) []byte {
	for _, file := range archive.File {
		if !strings.EqualFold(file.Name, name) {
			continue
		}
		handle, err := file.Open()
		if err != nil {
			log.Fatal(err)
		}
		defer handle.Close()
		payload, readErr := io.ReadAll(handle)
		if readErr != nil {
			log.Fatal(readErr)
		}
		return payload
	}
	return nil
}

// constantOperand 只認**靜態就知道值**的兩種運算元：`00h` 是位元組常數、
// `02h` 是字組常數（與 `internal/ecl` 的 `operandValue` 同一份讀法）。
// `01h`／`03h` 是記憶體參照——值要看執行時的記憶體，靜態掃不出來。
func constantOperand(operand ecl.Operand) (uint16, bool) {
	switch operand.Code {
	case 0x00:
		return uint16(operand.Low), true
	case 0x02:
		if !operand.WordSet {
			return 0, false
		}
		return operand.Word, true
	default:
		return 0, false
	}
}
