// Command render_previews creates deterministic README evidence from the
// original DAX assets and the same renderer-neutral parsers used by the game.
package main

import (
	"archive/zip"
	"encoding/json"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/wicanr2/Curse-of-the-Azure-Bonds-cht/internal/dax"
	"github.com/wicanr2/Curse-of-the-Azure-Bonds-cht/internal/geo"
	"github.com/wicanr2/Curse-of-the-Azure-Bonds-cht/internal/gfx"
	"github.com/wicanr2/Curse-of-the-Azure-Bonds-cht/internal/mapdata"
)

type spriteFrame struct {
	name string
	img  image.Image
}

type animationAssetRecord struct {
	Name  string `json:"name"`
	Delay uint32 `json:"delay"`
	X     int16  `json:"x"`
	Y     int16  `json:"y"`
}

func main() {
	if err := os.MkdirAll("docs/screenshots", 0755); err != nil {
		panic(err)
	}
	data, err := readMember("curseoftheazurebonds.zip", "TILES.DAX")
	if err != nil {
		panic(err)
	}
	blocks, err := dax.Parse(data)
	if err != nil {
		panic(err)
	}
	var pictures []gfx.Picture
	for _, block := range blocks {
		picture, err := gfx.ParsePicture(block.Data, false, 0)
		if err != nil {
			panic(err)
		}
		pictures = append(pictures, picture)
	}
	if err := renderTiles(pictures); err != nil {
		panic(err)
	}
	if err := renderCombatSprites(); err != nil {
		panic(err)
	}
	if err := renderCombatTerrain(); err != nil {
		panic(err)
	}
	if err := renderWilderness(pictures); err != nil {
		panic(err)
	}
	data, err = readMember("curseoftheazurebonds.zip", "GEO2.DAX")
	if err != nil {
		panic(err)
	}
	blocks, err = dax.Parse(data)
	if err != nil || len(blocks) == 0 {
		panic(fmt.Errorf("parse GEO2.DAX: %v", err))
	}
	grid, err := geo.Parse(blocks[0].Entry.ID, blocks[0].Data)
	if err != nil {
		panic(err)
	}
	if err := renderGeo(grid); err != nil {
		panic(err)
	}
	if err := renderDungeon(grid, pictures); err != nil {
		panic(err)
	}
}

func renderCombatTerrain() error {
	for _, source := range []string{"DUNGCOM.DAX", "WILDCOM.DAX", "RANDCOM.DAX"} {
		data, err := readMember("curseoftheazurebonds.zip", source)
		if err != nil {
			return err
		}
		blocks, err := dax.Parse(data)
		if err != nil || len(blocks) != 1 {
			return fmt.Errorf("parse %s: blocks=%d err=%v", source, len(blocks), err)
		}
		set, err := gfx.ParseCombatTiles(blocks[0].Data)
		if err != nil {
			return fmt.Errorf("parse %s combat tiles: %w", source, err)
		}
		const columns, cell, scale = 8, 56, 2
		rows := (len(set.Tiles) + columns - 1) / columns
		dst := image.NewRGBA(image.Rect(0, 0, columns*cell, rows*cell))
		fill(dst, color.RGBA{A: 255})
		for index, tile := range set.Tiles {
			rgba, err := tile.RGBA(0, gfx.EGA16)
			if err != nil {
				return err
			}
			drawScaled(dst, rgba, (index%columns)*cell+4, (index/columns)*cell+4, scale)
		}
		name := strings.ToLower(strings.TrimSuffix(source, ".DAX")) + "-tiles.png"
		if err := writePNG(filepath.Join("docs/screenshots", name), dst); err != nil {
			return err
		}
	}
	return nil
}

// renderCombatSprites extracts the small masked combat figures from the
// original COMSPR/SPRIT DAX members. The source DAX files remain local-only;
// the generated PNGs are the explicitly requested, renderer-ready assets.
func renderCombatSprites() error {
	if err := os.MkdirAll("assets/sprites", 0755); err != nil {
		return err
	}
	sources := []string{"COMSPR.DAX", "CHEAD.DAX", "CBODY.DAX"}
	for index := 1; index <= 6; index++ {
		sources = append(sources, fmt.Sprintf("CPIC%d.DAX", index))
	}
	for index := 1; index <= 6; index++ {
		sources = append(sources, fmt.Sprintf("SPRIT%d.DAX", index))
	}
	for index := 1; index <= 6; index++ {
		sources = append(sources, fmt.Sprintf("PIC%d.DAX", index))
	}
	for _, index := range []int{1, 2, 6} {
		sources = append(sources, fmt.Sprintf("BIGPIC%d.DAX", index))
	}
	for index := 2; index <= 6; index++ {
		sources = append(sources, fmt.Sprintf("HEAD%d.DAX", index), fmt.Sprintf("BODY%d.DAX", index))
	}
	frames := make([]spriteFrame, 0)
	animationAssets := make([]animationAssetRecord, 0)
	layers := make(map[string]map[uint8]gfx.Picture)
	var manifest strings.Builder
	manifest.WriteString("# Extracted combat sprites\n\n")
	manifest.WriteString("These PNGs were generated by `scripts/render_previews.go` from the local original DAX image. The DAX source itself is not redistributed. `maskColor=0` is rendered transparent.\n\n")
	manifest.WriteString("| source | block | item | size | output | status |\n|---|---:|---:|---:|---|---|\n")
	for _, source := range sources {
		data, err := readMember("curseoftheazurebonds.zip", source)
		if err != nil {
			return err
		}
		blocks, err := dax.Parse(data)
		if err != nil {
			return fmt.Errorf("parse %s: %w", source, err)
		}
		for _, block := range blocks {
			if strings.HasPrefix(source, "SPRIT") || strings.HasPrefix(source, "PIC") {
				xorFromFirst := strings.HasPrefix(source, "PIC")
				animation, err := gfx.ParseAnimationWithDelta(block.Data, true, 0, xorFromFirst)
				if err != nil {
					manifest.WriteString(fmt.Sprintf("| `%s` | `0x%02X` | — | — | — | skipped: `%s` |\n", source, block.Entry.ID, err))
					continue
				}
				stem := strings.TrimSuffix(source, filepath.Ext(source))
				for index, frame := range animation.Frames {
					img, err := frame.Picture.RGBA(0, gfx.EGA16)
					if err != nil {
						return fmt.Errorf("render %s block 0x%02X frame %d: %w", source, block.Entry.ID, index, err)
					}
					name := fmt.Sprintf("%s-block-%02X-frame-%02d.png", strings.ToLower(stem), block.Entry.ID, index)
					if err := writePNG(filepath.Join("assets/sprites", name), img); err != nil {
						return err
					}
					frames = append(frames, spriteFrame{name: name, img: img})
					animationAssets = append(animationAssets, animationAssetRecord{Name: name, Delay: frame.Delay, X: frame.Picture.X, Y: frame.Picture.Y})
					manifest.WriteString(fmt.Sprintf("| `%s` | `0x%02X` | frame %d (delay %d, x %d, y %d) | %dx%d | [`%s`](../../assets/sprites/%s) | animation extracted |\n", source, block.Entry.ID, index, frame.Delay, frame.Picture.X, frame.Picture.Y, frame.Picture.Width(), frame.Picture.Height(), name, name))
				}
				continue
			}
			masked := !strings.HasPrefix(source, "BIGPIC") && !strings.HasPrefix(source, "HEAD") && !strings.HasPrefix(source, "BODY")
			picture, err := gfx.ParsePicture(block.Data, masked, 0)
			if err != nil {
				manifest.WriteString(fmt.Sprintf("| `%s` | `0x%02X` | — | — | — | skipped: `%s` |\n", source, block.Entry.ID, err))
				continue
			}
			for item := 0; item < int(picture.ItemCount); item++ {
				img, err := picture.RGBA(item, gfx.EGA16)
				if err != nil {
					return fmt.Errorf("render %s block 0x%02X item %d: %w", source, block.Entry.ID, item, err)
				}
				stem := strings.TrimSuffix(source, filepath.Ext(source))
				name := fmt.Sprintf("%s-block-%02X-item-%02d.png", strings.ToLower(stem), block.Entry.ID, item)
				if err := writePNG(filepath.Join("assets/sprites", name), img); err != nil {
					return err
				}
				frames = append(frames, spriteFrame{name: name, img: img})
				if item == 0 && (source == "CHEAD.DAX" || source == "CBODY.DAX" || strings.HasPrefix(source, "HEAD") || strings.HasPrefix(source, "BODY")) {
					stem := strings.TrimSuffix(source, filepath.Ext(source))
					if layers[stem] == nil {
						layers[stem] = make(map[uint8]gfx.Picture)
					}
					layers[stem][block.Entry.ID] = picture
				}
				manifest.WriteString(fmt.Sprintf("| `%s` | `0x%02X` | %d | %dx%d | [`%s`](../../assets/sprites/%s) | extracted |\n", source, block.Entry.ID, item, picture.Width(), picture.Height(), name, name))
			}
		}
	}
	// CHEAD is the 10-row helmet/head layer and CBODY is the 24-row body
	// canvas. The reference merges the head into the body's top-left pixels.
	// Keep six deterministic composites ready for the current six-slot party;
	// later character data can select the exact head/body IDs without changing
	// the asset format.
	for id := uint8(0); id < 6; id++ {
		for _, variant := range []struct {
			suffix string
			offset uint8
		}{{suffix: "", offset: 0}, {suffix: "-attack", offset: 0x80}} {
			head, headOK := layers["CHEAD"][id+variant.offset]
			body, bodyOK := layers["CBODY"][id+variant.offset]
			if !headOK || !bodyOK {
				continue
			}
			merged, err := gfx.MergePictures(body, head)
			if err != nil {
				return fmt.Errorf("merge party icon 0x%02X%s: %w", id, variant.suffix, err)
			}
			img, err := merged.RGBA(0, gfx.EGA16)
			if err != nil {
				return err
			}
			name := fmt.Sprintf("party%s-head-%02X-body-%02X.png", variant.suffix, id, id)
			if err := writePNG(filepath.Join("assets/sprites", name), img); err != nil {
				return err
			}
			frames = append(frames, spriteFrame{name: name, img: img})
			manifest.WriteString(fmt.Sprintf("| `CHEAD+CBODY` | `0x%02X` | %s merged | %dx%d | [`%s`](../../assets/sprites/%s) | party layer composition |\n", id, variant.suffix, merged.Width(), merged.Height(), name, name))
		}
	}
	// General scene characters use HEAD<area> and BODY<area> pictures. The
	// reference draws the head at the origin and the body five 8-pixel text
	// rows below it (40 pixels), not five individual pixels.
	for area := 2; area <= 6; area++ {
		headLayers := layers[fmt.Sprintf("HEAD%d", area)]
		bodyLayers := layers[fmt.Sprintf("BODY%d", area)]
		ids := make([]int, 0, len(headLayers))
		for id := range headLayers {
			ids = append(ids, int(id))
		}
		sort.Ints(ids)
		for _, rawID := range ids {
			id := uint8(rawID)
			head := headLayers[id]
			body, ok := bodyLayers[id]
			if !ok {
				continue
			}
			merged, err := gfx.ComposeHeadBody(head, body, 5*8)
			if err != nil {
				return fmt.Errorf("merge HEAD%d/BODY%d block 0x%02X: %w", area, area, id, err)
			}
			img, err := merged.RGBA(0, gfx.EGA16)
			if err != nil {
				return err
			}
			name := fmt.Sprintf("character-area-%d-head-%02X-body-%02X.png", area, id, id)
			if err := writePNG(filepath.Join("assets/sprites", name), img); err != nil {
				return err
			}
			frames = append(frames, spriteFrame{name: name, img: img})
			manifest.WriteString(fmt.Sprintf("| `HEAD%d+BODY%d` | `0x%02X` | BODY y+40 px (5 rows) | %dx%d | [`%s`](../../assets/sprites/%s) | scene character composition |\n", area, area, id, merged.Width(), merged.Height(), name, name))
		}
		// ECL may combine independent HEAD/BODY selectors. Tilverton's Gond
		// altar is the first proven mixed pair: HEAD2 block 9 + BODY2 block 6.
		if area == 2 {
			head, headOK := headLayers[9]
			body, bodyOK := bodyLayers[6]
			if headOK && bodyOK {
				merged, err := gfx.ComposeHeadBody(head, body, 5*8)
				if err != nil {
					return fmt.Errorf("merge HEAD2 block 0x09/BODY2 block 0x06: %w", err)
				}
				img, err := merged.RGBA(0, gfx.EGA16)
				if err != nil {
					return err
				}
				name := "character-area-2-head-09-body-06.png"
				if err := writePNG(filepath.Join("assets/sprites", name), img); err != nil {
					return err
				}
				frames = append(frames, spriteFrame{name: name, img: img})
				manifest.WriteString(fmt.Sprintf("| `HEAD2 0x09 + BODY2 0x06` | mixed selectors | BODY y+40 px (5 rows) | %dx%d | [`%s`](../../assets/sprites/%s) | Gond altar ECL composition |\n", merged.Width(), merged.Height(), name, name))
			}
		}
	}
	if err := os.WriteFile("assets/sprites/README.md", []byte(manifest.String()), 0644); err != nil {
		return err
	}
	data, err := json.MarshalIndent(animationAssets, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile("assets/sprites/animation.json", append(data, '\n'), 0644); err != nil {
		return err
	}
	return writeSpriteSheet(frames)
}

func writeSpriteSheet(frames []spriteFrame) error {
	if len(frames) == 0 {
		return fmt.Errorf("no masked combat sprites were decoded")
	}
	const columns, cellWidth, cellHeight, scale = 8, 80, 80, 2
	rows := (len(frames) + columns - 1) / columns
	dst := image.NewRGBA(image.Rect(0, 0, columns*cellWidth, rows*cellHeight))
	fill(dst, color.RGBA{12, 18, 28, 255})
	for index, sprite := range frames {
		x := (index%columns)*cellWidth + 8
		y := (index/columns)*cellHeight + 8
		drawSpriteScaled(dst, sprite.img, x, y, scale)
	}
	return writePNG("docs/screenshots/combat-sprites.png", dst)
}

func drawSpriteScaled(dst *image.RGBA, src image.Image, x, y, scale int) {
	for yy := 0; yy < src.Bounds().Dy(); yy++ {
		for xx := 0; xx < src.Bounds().Dx(); xx++ {
			c := src.At(xx, yy)
			_, _, _, alpha := c.RGBA()
			if alpha == 0 {
				continue
			}
			for sy := 0; sy < scale; sy++ {
				for sx := 0; sx < scale; sx++ {
					dst.Set(x+xx*scale+sx, y+yy*scale+sy, c)
				}
			}
		}
	}
}

func readMember(path, name string) ([]byte, error) {
	archive, err := zip.OpenReader(path)
	if err != nil {
		return nil, err
	}
	defer archive.Close()
	for _, file := range archive.File {
		if file.Name != name {
			continue
		}
		r, err := file.Open()
		if err != nil {
			return nil, err
		}
		defer r.Close()
		return io.ReadAll(r)
	}
	return nil, fmt.Errorf("member %s not found", name)
}

func renderTiles(pictures []gfx.Picture) error {
	const scale, cellW, cellH = 2, 72, 52
	dst := image.NewRGBA(image.Rect(0, 0, 8*cellW, 6*cellH+32))
	fill(dst, color.RGBA{12, 18, 28, 255})
	index := 0
	for _, picture := range pictures {
		for item := 0; item < int(picture.ItemCount) && index < 48; item++ {
			rgba, err := picture.RGBA(item, gfx.EGA16)
			if err != nil {
				return err
			}
			x := (index%8)*cellW + 8
			y := (index/8)*cellH + 36
			drawScaled(dst, rgba, x, y, scale)
			index++
		}
	}
	return writePNG("docs/screenshots/tiles-gallery.png", dst)
}

func renderGeo(grid geo.Grid) error {
	const originX, originY, cell = 24, 32, 20
	wallColor := color.RGBA{80, 220, 235, 255}
	dst := image.NewRGBA(image.Rect(0, 0, 368, 368))
	fill(dst, color.RGBA{8, 20, 26, 255})
	for y := 0; y < geo.Height; y++ {
		for x := 0; x < geo.Width; x++ {
			fillRect(dst, originX+x*cell+1, originY+y*cell+1, cell-1, cell-1, color.RGBA{18, 42, 48, 255})
			walls := grid.Cells[y][x].WallDirections
			if walls[0] != 0 {
				line(dst, originX+x*cell, originY+y*cell, originX+(x+1)*cell, originY+y*cell, wallColor)
			}
			if walls[1] != 0 {
				line(dst, originX+(x+1)*cell, originY+y*cell, originX+(x+1)*cell, originY+(y+1)*cell, wallColor)
			}
			if walls[2] != 0 {
				line(dst, originX+x*cell, originY+(y+1)*cell, originX+(x+1)*cell, originY+(y+1)*cell, wallColor)
			}
			if walls[3] != 0 {
				line(dst, originX+x*cell, originY+y*cell, originX+x*cell, originY+(y+1)*cell, wallColor)
			}
		}
	}
	fillRect(dst, originX+2, originY+2, 6, 6, color.RGBA{255, 220, 80, 255})
	return writePNG("docs/screenshots/geo-geometry.png", dst)
}

func renderWilderness(pictures []gfx.Picture) error {
	const (
		scale    = 2
		tileSize = 24
		originX  = 24
		originY  = 32
		viewW    = 7
		viewH    = 5
	)
	floor := mapdata.GenerateWilderness(0, 1)
	dst := image.NewRGBA(image.Rect(0, 0, 384, 304))
	fill(dst, color.RGBA{12, 18, 28, 255})
	centerX, centerY := 25, 12
	for row := 0; row < viewH; row++ {
		for column := 0; column < viewW; column++ {
			x := centerX + column - viewW/2
			y := centerY + row - viewH/2
			entry, ok := floor.Entry(x, y)
			left := originX + column*tileSize*scale
			top := originY + row*tileSize*scale
			if ok {
				rgba, err := pictureRGBA(pictures, int(entry.TileIndex))
				if err != nil {
					return err
				}
				drawScaled(dst, rgba, left, top, scale)
			}
			if x == centerX && y == centerY {
				fillRect(dst, left+tileSize*scale/2-4, top+tileSize*scale/2-4, 8, 8, color.RGBA{255, 230, 80, 255})
			}
		}
	}
	return writePNG("docs/screenshots/wilderness-floor.png", dst)
}

func renderDungeon(grid geo.Grid, pictures []gfx.Picture) error {
	const (
		originX  = 24
		originY  = 32
		tileSize = 24
		viewW    = 13
		viewH    = 5
	)
	floor := mapdata.GenerateDungeon(grid, 8, 8)
	dst := image.NewRGBA(image.Rect(0, 0, 384, 192))
	fill(dst, color.RGBA{12, 18, 28, 255})
	for row := 0; row < viewH; row++ {
		for column := 0; column < viewW; column++ {
			entry, ok := floor.Entry(18+column, 8+row)
			if !ok {
				continue
			}
			rgba, err := pictureRGBA(pictures, int(entry.TileIndex))
			if err != nil {
				return err
			}
			drawScaled(dst, rgba, originX+column*tileSize, originY+row*tileSize, 1)
		}
	}
	return writePNG("docs/screenshots/dungeon-floor.png", dst)
}

func pictureRGBA(pictures []gfx.Picture, index int) (image.Image, error) {
	for _, picture := range pictures {
		if index < int(picture.ItemCount) {
			return picture.RGBA(index, gfx.EGA16)
		}
		index -= int(picture.ItemCount)
	}
	return nil, fmt.Errorf("TILES.DAX has no item %d", index)
}

func fill(dst *image.RGBA, c color.Color) {
	fillRect(dst, 0, 0, dst.Bounds().Dx(), dst.Bounds().Dy(), c)
}
func fillRect(dst *image.RGBA, x, y, w, h int, c color.Color) {
	for yy := y; yy < y+h; yy++ {
		for xx := x; xx < x+w; xx++ {
			dst.Set(xx, yy, c)
		}
	}
}
func drawScaled(dst *image.RGBA, src image.Image, x, y, scale int) {
	for yy := 0; yy < src.Bounds().Dy(); yy++ {
		for xx := 0; xx < src.Bounds().Dx(); xx++ {
			c := src.At(xx, yy)
			for sy := 0; sy < scale; sy++ {
				for sx := 0; sx < scale; sx++ {
					dst.Set(x+xx*scale+sx, y+yy*scale+sy, c)
				}
			}
		}
	}
}
func line(dst *image.RGBA, x1, y1, x2, y2 int, c color.Color) {
	if x1 == x2 {
		for y := y1; y <= y2; y++ {
			dst.Set(x1, y, c)
		}
		return
	}
	for x := x1; x <= x2; x++ {
		dst.Set(x, y1, c)
	}
}
func writePNG(path string, img image.Image) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return png.Encode(f, img)
}
