// Command render_previews creates deterministic README evidence from the
// original DAX assets and the same renderer-neutral parsers used by the game.
package main

import (
	"archive/zip"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/wicanr2/Curse-of-the-Azure-Bonds-cht/internal/dax"
	"github.com/wicanr2/Curse-of-the-Azure-Bonds-cht/internal/geo"
	"github.com/wicanr2/Curse-of-the-Azure-Bonds-cht/internal/gfx"
	"github.com/wicanr2/Curse-of-the-Azure-Bonds-cht/internal/mapdata"
)

type spriteFrame struct {
	name string
	img  image.Image
}

func main() {
	if err := os.MkdirAll("docs/screenshots", 0755); err != nil {
		panic(err)
	}
	data, err := readMember("curseoftheazurebonds.zip", "TILES.DAX")
	if err != nil {
		panic(err)
	}
	blocks, err := dax.Parse(data)
	if err != nil {
		panic(err)
	}
	var pictures []gfx.Picture
	for _, block := range blocks {
		picture, err := gfx.ParsePicture(block.Data, false, 0)
		if err != nil {
			panic(err)
		}
		pictures = append(pictures, picture)
	}
	if err := renderTiles(pictures); err != nil {
		panic(err)
	}
	if err := renderCombatSprites(); err != nil {
		panic(err)
	}
	if err := renderWilderness(pictures); err != nil {
		panic(err)
	}
	data, err = readMember("curseoftheazurebonds.zip", "GEO2.DAX")
	if err != nil {
		panic(err)
	}
	blocks, err = dax.Parse(data)
	if err != nil || len(blocks) == 0 {
		panic(fmt.Errorf("parse GEO2.DAX: %v", err))
	}
	grid, err := geo.Parse(blocks[0].Entry.ID, blocks[0].Data)
	if err != nil {
		panic(err)
	}
	if err := renderGeo(grid); err != nil {
		panic(err)
	}
	if err := renderDungeon(grid, pictures); err != nil {
		panic(err)
	}
}

// renderCombatSprites extracts the small masked combat figures from the
// original COMSPR/SPRIT DAX members. The source DAX files remain local-only;
// the generated PNGs are the explicitly requested, renderer-ready assets.
func renderCombatSprites() error {
	if err := os.MkdirAll("assets/sprites", 0755); err != nil {
		return err
	}
	sources := []string{"COMSPR.DAX"}
	for index := 1; index <= 6; index++ {
		sources = append(sources, fmt.Sprintf("CPIC%d.DAX", index))
	}
	for index := 1; index <= 6; index++ {
		sources = append(sources, fmt.Sprintf("SPRIT%d.DAX", index))
	}
	frames := make([]spriteFrame, 0)
	var manifest strings.Builder
	manifest.WriteString("# Extracted combat sprites\n\n")
	manifest.WriteString("These PNGs were generated by `scripts/render_previews.go` from the local original DAX image. The DAX source itself is not redistributed. `maskColor=0` is rendered transparent.\n\n")
	manifest.WriteString("| source | block | item | size | output | status |\n|---|---:|---:|---:|---|---|\n")
	for _, source := range sources {
		data, err := readMember("curseoftheazurebonds.zip", source)
		if err != nil {
			return err
		}
		blocks, err := dax.Parse(data)
		if err != nil {
			return fmt.Errorf("parse %s: %w", source, err)
		}
		for _, block := range blocks {
			if strings.HasPrefix(source, "SPRIT") {
				animation, err := gfx.ParseAnimation(block.Data, true, 0)
				if err != nil {
					manifest.WriteString(fmt.Sprintf("| `%s` | `0x%02X` | — | — | — | skipped: `%s` |\n", source, block.Entry.ID, err))
					continue
				}
				stem := strings.TrimSuffix(source, filepath.Ext(source))
				for index, frame := range animation.Frames {
					img, err := frame.Picture.RGBA(0, gfx.EGA16)
					if err != nil {
						return fmt.Errorf("render %s block 0x%02X frame %d: %w", source, block.Entry.ID, index, err)
					}
					name := fmt.Sprintf("%s-block-%02X-frame-%02d.png", strings.ToLower(stem), block.Entry.ID, index)
					if err := writePNG(filepath.Join("assets/sprites", name), img); err != nil {
						return err
					}
					frames = append(frames, spriteFrame{name: name, img: img})
					manifest.WriteString(fmt.Sprintf("| `%s` | `0x%02X` | frame %d (delay %d) | %dx%d | [`%s`](../../assets/sprites/%s) | animation extracted |\n", source, block.Entry.ID, index, frame.Delay, frame.Picture.Width(), frame.Picture.Height(), name, name))
				}
				continue
			}
			picture, err := gfx.ParsePicture(block.Data, true, 0)
			if err != nil {
				manifest.WriteString(fmt.Sprintf("| `%s` | `0x%02X` | — | — | — | skipped: `%s` |\n", source, block.Entry.ID, err))
				continue
			}
			for item := 0; item < int(picture.ItemCount); item++ {
				img, err := picture.RGBA(item, gfx.EGA16)
				if err != nil {
					return fmt.Errorf("render %s block 0x%02X item %d: %w", source, block.Entry.ID, item, err)
				}
				stem := strings.TrimSuffix(source, filepath.Ext(source))
				name := fmt.Sprintf("%s-block-%02X-item-%02d.png", strings.ToLower(stem), block.Entry.ID, item)
				if err := writePNG(filepath.Join("assets/sprites", name), img); err != nil {
					return err
				}
				frames = append(frames, spriteFrame{name: name, img: img})
				manifest.WriteString(fmt.Sprintf("| `%s` | `0x%02X` | %d | %dx%d | [`%s`](../../assets/sprites/%s) | extracted |\n", source, block.Entry.ID, item, picture.Width(), picture.Height(), name, name))
			}
		}
	}
	if err := os.WriteFile("assets/sprites/README.md", []byte(manifest.String()), 0644); err != nil {
		return err
	}
	return writeSpriteSheet(frames)
}

func writeSpriteSheet(frames []spriteFrame) error {
	if len(frames) == 0 {
		return fmt.Errorf("no masked combat sprites were decoded")
	}
	const columns, cellWidth, cellHeight, scale = 8, 80, 80, 2
	rows := (len(frames) + columns - 1) / columns
	dst := image.NewRGBA(image.Rect(0, 0, columns*cellWidth, rows*cellHeight))
	fill(dst, color.RGBA{12, 18, 28, 255})
	for index, sprite := range frames {
		x := (index%columns)*cellWidth + 8
		y := (index/columns)*cellHeight + 8
		drawSpriteScaled(dst, sprite.img, x, y, scale)
	}
	return writePNG("docs/screenshots/combat-sprites.png", dst)
}

func drawSpriteScaled(dst *image.RGBA, src image.Image, x, y, scale int) {
	for yy := 0; yy < src.Bounds().Dy(); yy++ {
		for xx := 0; xx < src.Bounds().Dx(); xx++ {
			c := src.At(xx, yy)
			_, _, _, alpha := c.RGBA()
			if alpha == 0 {
				continue
			}
			for sy := 0; sy < scale; sy++ {
				for sx := 0; sx < scale; sx++ {
					dst.Set(x+xx*scale+sx, y+yy*scale+sy, c)
				}
			}
		}
	}
}

func readMember(path, name string) ([]byte, error) {
	archive, err := zip.OpenReader(path)
	if err != nil {
		return nil, err
	}
	defer archive.Close()
	for _, file := range archive.File {
		if file.Name != name {
			continue
		}
		r, err := file.Open()
		if err != nil {
			return nil, err
		}
		defer r.Close()
		return io.ReadAll(r)
	}
	return nil, fmt.Errorf("member %s not found", name)
}

func renderTiles(pictures []gfx.Picture) error {
	const scale, cellW, cellH = 2, 72, 52
	dst := image.NewRGBA(image.Rect(0, 0, 8*cellW, 6*cellH+32))
	fill(dst, color.RGBA{12, 18, 28, 255})
	index := 0
	for _, picture := range pictures {
		for item := 0; item < int(picture.ItemCount) && index < 48; item++ {
			rgba, err := picture.RGBA(item, gfx.EGA16)
			if err != nil {
				return err
			}
			x := (index%8)*cellW + 8
			y := (index/8)*cellH + 36
			drawScaled(dst, rgba, x, y, scale)
			index++
		}
	}
	return writePNG("docs/screenshots/tiles-gallery.png", dst)
}

func renderGeo(grid geo.Grid) error {
	const originX, originY, cell = 24, 32, 20
	wallColor := color.RGBA{80, 220, 235, 255}
	dst := image.NewRGBA(image.Rect(0, 0, 368, 368))
	fill(dst, color.RGBA{8, 20, 26, 255})
	for y := 0; y < geo.Height; y++ {
		for x := 0; x < geo.Width; x++ {
			fillRect(dst, originX+x*cell+1, originY+y*cell+1, cell-1, cell-1, color.RGBA{18, 42, 48, 255})
			walls := grid.Cells[y][x].WallDirections
			if walls[0] != 0 {
				line(dst, originX+x*cell, originY+y*cell, originX+(x+1)*cell, originY+y*cell, wallColor)
			}
			if walls[1] != 0 {
				line(dst, originX+(x+1)*cell, originY+y*cell, originX+(x+1)*cell, originY+(y+1)*cell, wallColor)
			}
			if walls[2] != 0 {
				line(dst, originX+x*cell, originY+(y+1)*cell, originX+(x+1)*cell, originY+(y+1)*cell, wallColor)
			}
			if walls[3] != 0 {
				line(dst, originX+x*cell, originY+y*cell, originX+x*cell, originY+(y+1)*cell, wallColor)
			}
		}
	}
	fillRect(dst, originX+2, originY+2, 6, 6, color.RGBA{255, 220, 80, 255})
	return writePNG("docs/screenshots/geo-geometry.png", dst)
}

func renderWilderness(pictures []gfx.Picture) error {
	const (
		scale    = 2
		tileSize = 24
		originX  = 24
		originY  = 32
		viewW    = 7
		viewH    = 5
	)
	floor := mapdata.GenerateWilderness(0, 1)
	dst := image.NewRGBA(image.Rect(0, 0, 384, 304))
	fill(dst, color.RGBA{12, 18, 28, 255})
	centerX, centerY := 25, 12
	for row := 0; row < viewH; row++ {
		for column := 0; column < viewW; column++ {
			x := centerX + column - viewW/2
			y := centerY + row - viewH/2
			entry, ok := floor.Entry(x, y)
			left := originX + column*tileSize*scale
			top := originY + row*tileSize*scale
			if ok {
				rgba, err := pictureRGBA(pictures, int(entry.TileIndex))
				if err != nil {
					return err
				}
				drawScaled(dst, rgba, left, top, scale)
			}
			if x == centerX && y == centerY {
				fillRect(dst, left+tileSize*scale/2-4, top+tileSize*scale/2-4, 8, 8, color.RGBA{255, 230, 80, 255})
			}
		}
	}
	return writePNG("docs/screenshots/wilderness-floor.png", dst)
}

func renderDungeon(grid geo.Grid, pictures []gfx.Picture) error {
	const (
		originX  = 24
		originY  = 32
		tileSize = 24
		viewW    = 13
		viewH    = 5
	)
	floor := mapdata.GenerateDungeon(grid, 8, 8)
	dst := image.NewRGBA(image.Rect(0, 0, 384, 192))
	fill(dst, color.RGBA{12, 18, 28, 255})
	for row := 0; row < viewH; row++ {
		for column := 0; column < viewW; column++ {
			entry, ok := floor.Entry(18+column, 8+row)
			if !ok {
				continue
			}
			rgba, err := pictureRGBA(pictures, int(entry.TileIndex))
			if err != nil {
				return err
			}
			drawScaled(dst, rgba, originX+column*tileSize, originY+row*tileSize, 1)
		}
	}
	return writePNG("docs/screenshots/dungeon-floor.png", dst)
}

func pictureRGBA(pictures []gfx.Picture, index int) (image.Image, error) {
	for _, picture := range pictures {
		if index < int(picture.ItemCount) {
			return picture.RGBA(index, gfx.EGA16)
		}
		index -= int(picture.ItemCount)
	}
	return nil, fmt.Errorf("TILES.DAX has no item %d", index)
}

func fill(dst *image.RGBA, c color.Color) {
	fillRect(dst, 0, 0, dst.Bounds().Dx(), dst.Bounds().Dy(), c)
}
func fillRect(dst *image.RGBA, x, y, w, h int, c color.Color) {
	for yy := y; yy < y+h; yy++ {
		for xx := x; xx < x+w; xx++ {
			dst.Set(xx, yy, c)
		}
	}
}
func drawScaled(dst *image.RGBA, src image.Image, x, y, scale int) {
	for yy := 0; yy < src.Bounds().Dy(); yy++ {
		for xx := 0; xx < src.Bounds().Dx(); xx++ {
			c := src.At(xx, yy)
			for sy := 0; sy < scale; sy++ {
				for sx := 0; sx < scale; sx++ {
					dst.Set(x+xx*scale+sx, y+yy*scale+sy, c)
				}
			}
		}
	}
}
func line(dst *image.RGBA, x1, y1, x2, y2 int, c color.Color) {
	if x1 == x2 {
		for y := y1; y <= y2; y++ {
			dst.Set(x1, y, c)
		}
		return
	}
	for x := x1; x <= x2; x++ {
		dst.Set(x, y1, c)
	}
}
func writePNG(path string, img image.Image) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return png.Encode(f, img)
}
